"ID","NAME","TYPE","BILLINGSTREET","BILLINGCITY","BILLINGSTATE","BILLINGPOSTALCODE","BILLINGCOUNTRY","SHIPPINGSTREET","SHIPPINGCITY","SHIPPINGSTATE","SHIPPINGPOSTALCODE","SHIPPINGCOUNTRY","PHONE","ACCOUNTNUMBER","WEBSITE","INDUSTRY"
"001U0000003MhzcIAC","University of Arizona123","Customer - Direct","888 N Euclid 
Hallis Center, Room 501
Tucson, AZ 85721
United States","Tucson","AZ","","USA","888 N Euclid 
Hallis Center, Room 501
Tucson, AZ 85721
United States","","","","","(520) 773-9050","CD736025","www.universityofarizona.com","Education"
"001U0000003MhzdIAC","United Oil & Gas Corp.123","Customer - Direct","1301 Avenue of the Americas 
New York, NY 10019
USA","New York","NY","","USA","1301 Avenue of the Americas 
New York, NY 10019
USA","","","","","(212) 842-5500","CD355118","http://www.uos.com","Energy"
"001U0000003MhzeIAC","sForce","Customer - Direct","The Landmark @ One Market","San Francisco","CA","94087","US","","","","","","(415) 901-7000","","www.sforce.com","Hospitality"
"001U0000003MhzTIAS","GenePoint","Customer - Channel","345 Shoreline Park
Mountain View, CA 94043
USA","Mountain View","CA","","USA","345 Shoreline Park
Mountain View, CA 94043
USA","","","","","(650) 867-3450","CC978213","www.genepoint.com","Biotechnology"
"001U0000003MhzUIAS","United Oil & Gas, UK123","Customer - Direct","Kings Park, 17th Avenue, Team Valley Trading Estate,
Gateshead, Tyne and Wear NE26 3HS
United Kingdom","","UK","","USA","Kings Park, 17th Avenue, Team Valley Trading Estate,
Gateshead, Tyne and Wear NE26 3HS
United Kingdom","","","","","+44 191 4956203","CD355119-A","http://www.uos.com","Biotechnology"
"001U0000003MhzVIAS","United Oil & Gas, Singapore123","Customer - Direct","9 Tagore Lane
Singapore, Singapore 787472
Singapore","Singapore","Singapore","","USA","9 Tagore Lane
Singapore, Singapore 787472
Singapore","","","","","(650) 450-8810","CD355120-B","http://www.uos.com","Energy"
"001U0000003MhzWIAS","Edge Communications123","Customer - Direct","312 Constitution Place
Austin, TX 78767
USA","Austin","TX","","USA","312 Constitution Place
Austin, TX 78767
USA","","","","","(512) 757-6000","CD451796","http://edgecomm.com","Electronics"
"001U0000003MhzXIAS","Burlington Textiles Corp of America123","Customer - Direct","525 S. Lexington Ave","Burlington","NC","27215","USA","","","","","","(336) 222-7000","CD656092","www.burlington.com","Apparel"
"001U0000003MhzYIAS","Pyramid Construction Inc.123","Customer - Channel","2 Place Jussieu","Paris","","75251","France","2 Place Jussieu","Paris","","75251","France","(014) 427-4427","CC213425","www.pyramid.com","Manufacturing"
"001U0000003MhzZIAS","Dickenson plc","Customer - Channel","1301 Hoch Drive","Lawrence","KS","66045","USA","1301 Hoch Drive","Lawrence","KS","66045","USA","(785) 241-6200","CC634267","dickenson-consulting.com","Consulting"
"001U0000003MhzaIAC","Grand Hotels & Resorts Ltd 001","Customer - Direct","2334 N. Michigan Avenue, Suite 1500
Chicago, IL 60601, USA","Chicago","IL","","USA","2334 N. Michigan Avenue, Suite 1500
Chicago, IL 60601, USA","","","","","(312) 596-1000","CD439877","www.grandhotels.com","Hospitality"
"001U0000003MhzbIAC","Express Logistics and Transport123","Customer - Channel","620 SW 5th Avenue Suite 400
Portland, Oregon 97204
United States","Portland","OR","","USA","620 SW 5th Avenue Suite 400
Portland, Oregon 97204
United States","","","","","(503) 421-7800","CC947211","www.expressl&t.net","Transportation"
"001U0000002ZpYsIAK","Test My Mobile Company123","","","","","","USA","","","","","","","","","Finance"
"001U000000H08q5IAB","test","","","","","","USA","","","","","","","","","Entertainment"
"001U000001XVSuTIAX","Farmers Coop. of Florida","","321 Westcott Building","Tallahassee","FL","32306","USA","","","","","","(850) 644-4200","","","Agriculture"
"001U000000mGl9aIAC","Zenith Industrial Partners","","","","OH","","USA","","","","","","(614) 431-5000","","",""
"001U000000mGm7jIAC","Aethna Home Products","","","","VA","","USA","","","","","","(434) 369-3100","","",""
